---
- name: Module 3 - basic web server setup
  hosts: rhel_web
  become: true
  gather_facts: true

  tasks:

    - name: Install the web package
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Ensure the web service is running
      ansible.builtin.service:
        name: httpd
        state: started

