---
galaxy_info:
  role_name: web_config
  author: Charter Automation Team
  description: Installs and configures a simple web server for training.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
dependencies: []
