---
galaxy_info:
  author: Charter Ansible Training
  description: Install and configure an Apache web server
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

    - name: Ubuntu
      versions:
        - "11"
        - "12"

dependencies: []